name: Continuous Delivery

on:
  push:
    branches:
      - master

jobs:
  latest:
    name: Latest
    if: ${{contains(github.event.head_commit.message, format('chore(release){0} logger@', ':'))}}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('./bun.lock', './bun.lockb') }}

      - name: Cache Temporary Build Artifacts (.cache)
        id: cache-tmp
        uses: actions/cache@v4
        with:
          path: ./.cache
          key: ${{ runner.os }}-cache-${{ hashFiles('./.cache/dts-cache.json') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      - name: Install Dependencies
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: bun install --frozen-lockfile

      - name: Build
        run: bun run build

      - name: Publish to NPM
        run: bun publish --registry=https://registry.npmjs.org --tag=latest
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to GitHub
        run: bun publish --registry=https://npm.pkg.github.com --tag=latest
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
